---
output: pdf_document
---

# Andrew Moore, `r format(Sys.Date(), "%m/%d/%Y")`

## MATH-471, Homework 3.1

```{r seed, echo = FALSE}
set.seed(20210922)
```

### 1. Generate samples of n = 100 for 10 different distributions.

```{r}
samples <- list(
  "A. Uniform"     = runif(100, 2, 5), 
  "B. Binomial"    = rbinom(100, 25, 0.1), 
  "C. Exponential" = rexp(100, 10), 
  "D. Gamma"       = rgamma(100, 8, 10), 
  "E. T"           = rt(100, 25), 
  "F. F"           = rf(100, 15, 15), 
  "G. Chisquare"   = rchisq(100, 9), 
  "H. Weibull"     = rweibull(100, 1, 1.5), 
  "I. Cauchy"      = rcauchy(100, 0, 1), 
  "J. Normal"      = rnorm(100, 0, 1)
)
```

### 2. Create histograms for each of the 10 distributions, and describe their shapes.

```{r}
par(mfrow = c(2, 3))

for (i in 1:6) hist(samples[[i]], main = names(samples)[i], xlab = "")
```

\newpage

```{r, fig.height = 5.6}
par(mfrow = c(2, 2))

for (i in 7:10) hist(samples[[i]], main = names(samples)[i], xlab = "")
```

\newpage

### 3. Use QQ-plots to determine if the sample comes from a *normal* distribution.

```{r}
par(mfrow = c(2, 3))

for (i in 1:6) {
  qqnorm(samples[[i]], main = LETTERS[i])
  qqline(samples[[i]])
}
```

```{r}
par(mfrow = c(2, 2))

for (i in 7:10) {
  qqnorm(samples[[i]], main = LETTERS[i])
  qqline(samples[[i]])
}
```
